market: "bfsp_uk_place"
stake: 1.0
bins:
  - name: "bsp_1_01_1_20"
    bsp_min: 1.01
    bsp_max: 1.20

  - name: "bsp_1_20_1_50"
    bsp_min: 1.20
    bsp_max: 1.50

  - name: "bsp_1_50_2_00"
    bsp_min: 1.50
    bsp_max: 2.00

  - name: "bsp_2_00_3_00"
    bsp_min: 2.00
    bsp_max: 3.00

  - name: "bsp_3_00_5_00"
    bsp_min: 3.00
    bsp_max: 5.00

  - name: "bsp_5_00_10_00"
    bsp_min: 5.00
    bsp_max: 10.00

  - name: "bsp_10_00_20_00"
    bsp_min: 10.00
    bsp_max: 20.00

  - name: "bsp_20_00_1000"
    bsp_min: 20.00
    bsp_max: 1000000.0